#ifndef _KD_CAMERA_HW_H_
#define _KD_CAMERA_HW_H_
 

#include <mach/mt_gpio.h>
#include <mach/mt_pm_ldo.h>

//Power 
#define CAMERA_POWER_VCAM_A MT6323_POWER_LDO_VCAMA
#define CAMERA_POWER_VCAM_D_MAIN MT6323_POWER_LDO_VCAMD
#define CAMERA_POWER_VCAM_D_SUB MT6323_POWER_LDO_VCAMD
#define CAMERA_POWER_VCAM_IO MT6323_POWER_LDO_VCAM_IO
#define CAMERA_POWER_VCAM_AF MT6323_POWER_LDO_VCAM_AF

#endif 
